import type { Guide } from './types';

export const anthropicApi: Guide = {
    slug: 'anthropic-api',
    tag: 'GUIDE \u00B7 ANTHROPIC API',
    title: 'Anthropic API: Bygg med Claude',
    description: 'Lær hvordan du bruker Anthropic API til å bygge AI-applikasjoner med Claude. Komplett guide til oppsett, autentisering, modellvalg mellom Opus, Sonnet og Haiku, priser og avanserte funksjoner som tool use, vision og extended thinking.',
    keywords: ['anthropic api', 'claude api', 'claude sdk', 'anthropic norsk', 'claude sonnet api', 'claude opus api'],
    publishedDate: '2026-02-10',
    relatedSlugs: ['claude-code', 'openai-api', 'bygg-ai-chatbot'],
    category: 'bygg-med-ai',
    sections: [
        {
            heading: 'Hva er Anthropic API?',
            content: 'Anthropic API gir deg programmatisk tilgang til Claude-modellene, slik at du kan bygge egne AI-drevne applikasjoner. I stedet for å bruke Claude gjennom nettsiden claude.ai, sender du forespørsler direkte fra koden din og får svar tilbake som du kan bruke akkurat slik du vil. Du bestemmer brukergrensesnittet, logikken og hvordan svarene presenteres.\n\nDokumentasjonen finner du på docs.anthropic.com, og det er der du bør starte. Den dekker alt fra grunnleggende API-kall til avanserte funksjoner. For å administrere kontoen din, opprette API-nøkler og overvåke forbruk bruker du console.anthropic.com, som er Anthropics utviklerportal.\n\nAnthropic tilbyr tre modellfamilier gjennom API-et: Opus, Sonnet og Haiku. Claude Opus 4.6 er den mest avanserte modellen med best kvalitet på kompleks resonnering og koding. Claude Sonnet 4.5 er arbeidshesten som gir en sterk balanse mellom kvalitet, hastighet og pris. Claude Haiku 4.5 er den raskeste og billigste, perfekt for enkle oppgaver og høyt volum. Alle modellene er tilgjengelige via det samme Messages API-endepunktet, så du kan bytte mellom dem ved å endre en enkelt parameter.'
        },
        {
            heading: 'Oppsett og autentisering',
            content: 'For å komme i gang trenger du en konto på console.anthropic.com. Registrering er gratis, men du må legge til en betalingsmetode for å bruke API-et. Det er ingen fast månedspris. Du betaler kun for det du faktisk bruker, basert på antall tokens du sender og mottar.\n\nNeste steg er å opprette en API-nøkkel. Gå til API Keys-seksjonen i console.anthropic.com og klikk «Create Key». Nøkkelen vises bare en gang, så kopier den umiddelbart og lagre den på et trygt sted. Denne nøkkelen autentiserer alle API-kallene dine, og du sender den med i headeren x-api-key på hver forespørsel.\n\nBeste praksis er å lagre nøkkelen som en miljøvariabel. Opprett en .env-fil i prosjektet ditt med linjen ANTHROPIC_API_KEY=din-nøkkel-her, og sørg for at .env er lagt til i .gitignore så den ikke havner på GitHub. I produksjon bruker du hemmelighetsbehandling i skyplattformen din, som Vercel Environment Variables eller lignende.\n\nFor de fleste språk finnes det offisielle SDK-er som forenkler API-kallene. I JavaScript og TypeScript installerer du Anthropics offisielle SDK med «npm install @anthropic-ai/sdk». Det finnes også en offisiell Python-pakke som heter «anthropic» og installeres med «pip install anthropic». SDK-ene håndterer autentisering, feilhåndtering og typing automatisk, slik at du slipper å jobbe med rå HTTP-kall.'
        },
        {
            heading: 'Ditt første API-kall',
            content: 'Anthropic bruker Messages API som hovedendepunkt. Du sender en POST-forespørsel til api.anthropic.com/v1/messages med en modell, maks antall output-tokens, og en liste med meldinger. Hver melding har en rolle (user eller assistant) og innhold. I tillegg kan du sende med et system-prompt som en separat parameter for å sette konteksten for samtalen.\n\nMed TypeScript-SDK-en ser det slik ut: Du importerer Anthropic fra @anthropic-ai/sdk, oppretter en klient som automatisk leser ANTHROPIC_API_KEY fra miljøvariablene, og kaller client.messages.create med modell (for eksempel «claude-sonnet-4-5-20250929»), max_tokens, og en meldingsarray. Svaret inneholder en content-array med tekstblokker, og du finner den genererte teksten i content[0].text. Du får også metadata om token-forbruk i usage-feltet.\n\nFor sanntidsopplevelser støtter API-et streaming. Sett stream til true, og du får svaret ord for ord i stedet for å vente på hele teksten. Med SDK-en bruker du client.messages.stream() som gir deg en stream du kan iterere over med for-await-løkken. Streaming er spesielt viktig for brukergrensesnitt der du vil vise teksten etter hvert som den genereres, noe som gir en mye bedre opplevelse enn å vente i flere sekunder på et komplett svar.\n\nEt viktig konsept er tokens. En token er omtrent tre til fire tegn på norsk. Både input-tokens (det du sender) og output-tokens (det modellen svarer) telles og faktureres. Bruk max_tokens-parameteren for å begrense lengden på svarene og holde kostnadene under kontroll. Du kan se detaljert token-forbruk i usage-feltet i hvert API-svar.'
        },
        {
            heading: 'Modeller og priser',
            content: 'Claude Opus 4.6 er Anthropics mest avanserte modell. Den utmerker seg på kompleks resonnering, avansert koding, kreativ skriving og oppgaver som krever dyp forståelse. Modell-ID-en er «claude-opus-4-6». Opus koster 5 dollar per million input-tokens og 25 dollar per million output-tokens. Du bruker Opus når kvaliteten må være best mulig og du er villig til å betale mer for det, for eksempel i kodegenerering, forskningsoppgaver eller avansert analyse.\n\nClaude Sonnet 4.5 er arbeidshesten i Claude-familien og den modellen de fleste utviklere bør starte med. Den gir utmerket kvalitet på de fleste oppgaver til en vesentlig lavere pris enn Opus. Modell-ID-en er «claude-sonnet-4-5-20250929». Sonnet koster 3 dollar per million input-tokens og 15 dollar per million output-tokens. For de aller fleste produksjonsapplikasjoner er Sonnet det naturlige valget fordi den gir en sterk balanse mellom kvalitet, hastighet og kostnad.\n\nClaude Haiku 4.5 er den raskeste og billigste modellen, designet for oppgaver der hastighet og volum er viktigere enn maks kvalitet. Modell-ID-en er «claude-haiku-4-5-20251001». Haiku koster 1 dollar per million input-tokens og 5 dollar per million output-tokens. Den er ideell for klassifisering, enkel tekstbehandling, kundestøttetriage og andre oppgaver der du trenger raske svar i stort volum uten å sprenge budsjettet.\n\nEn smart strategi er å bruke forskjellige modeller til forskjellige oppgaver. Bruk Haiku for enkel routing og klassifisering, Sonnet for de fleste produksjonsoppgaver, og Opus bare for de mest krevende oppgavene. Du kan sette forbruksgrenser i console.anthropic.com for å unngå overraskelser på fakturaen, og API-et støtter prompt caching som kan redusere input-kostnadene med opptil 90 prosent for gjentatte system-prompts.'
        },
        {
            heading: 'Avanserte funksjoner',
            content: 'Tool use (funksjonskalling) lar Claude kalle funksjoner du har definert. Du beskriver verktøyene dine med navn, beskrivelse og input-skjema i JSON Schema-format, og Claude bestemmer selv når det er relevant å bruke dem. Hvis du for eksempel definerer et verktøy for å hente værdata og brukeren spør om været, returnerer Claude et strukturert kall til det verktøyet. Du kjører funksjonen, sender resultatet tilbake, og Claude formulerer et svar basert på de faktiske dataene. Dette gjør det mulig å bygge AI-assistenter som kan samhandle med databaser, API-er og eksterne systemer.\n\nVision-funksjonaliteten lar deg sende bilder sammen med tekst i API-kallet. Du kan analysere skjermbilder, tolke diagrammer, lese tekst fra bilder, eller få Claude til å beskrive visuelt innhold. Bildene sendes som base64-kodet data eller som URL-er i meldingsarrayen. Alle tre modellene støtter vision, så du kan bruke Haiku for rask bildebehandling i volum eller Opus for detaljert bildeanalyse.\n\nExtended thinking er en funksjon som lar Claude bruke ekstra tid på å tenke gjennom komplekse problemer før den gir et svar. Når du aktiverer extended thinking, får du tilgang til modellens resonneringsprosess i tillegg til det endelige svaret. Dette er spesielt nyttig for matematikk, logikk, kodingsoppgaver og andre scenarier der stegvis resonnering gir bedre resultater. Du kan sette en budsjettparameter for hvor mange tokens Claude kan bruke på tenking.\n\nPrompt caching er en kostnadsbesparende funksjon som lagrer hyppig brukte deler av prompten, som system-instruksjoner og store dokumenter, slik at du ikke betaler full pris for å sende dem igjen. Cache-input koster betydelig mindre enn vanlige input-tokens. I tillegg støtter API-et batching for å sende mange forespørsler samtidig til redusert pris, og du kan bruke JSON mode for å sikre at Claude returnerer gyldig JSON i svaret.'
        },
        {
            heading: 'Claude API vs. OpenAI API: Forskjeller og valg',
            content: 'Den største forskjellen i API-design er at Anthropic bruker Messages API med et separat system-parameter, mens OpenAI bruker Chat Completions med system-rollen som en del av meldingsarrayen. I praksis er forskjellen liten, og begge SDK-ene er enkle å jobbe med. Anthropic bruker headeren x-api-key for autentisering, mens OpenAI bruker Authorization Bearer. Begge støtter streaming, tool use og vision.\n\nPå modellsiden tilbyr Anthropic tre tydelige nivåer med Opus, Sonnet og Haiku, mens OpenAI har et bredere utvalg med GPT-5, GPT-4.1 og o-serien for resonnering. Claude Sonnet 4.5 og GPT-4.1 er sammenlignbare i pris og kvalitet for de fleste oppgaver. Claudes extended thinking konkurrerer med OpenAIs o3-modeller for resonneringsoppgaver. Et viktig poeng er at Claude generelt har et større kontekstvindu på opptil 200 000 tokens, noe som gjør den spesielt sterk for oppgaver som involverer lange dokumenter.\n\nNår det gjelder unike styrker, er Claude kjent for å følge instruksjoner presist, håndtere lange kontekster godt, og ha en mer nyansert og forsiktig tilnærming til sensitiv informasjon. OpenAI har et bredere økosystem med embeddings, bilde- og lydgenerering, og fine-tuning. Mange utviklere bruker begge: Anthropic for oppgaver der presisjon og lange kontekster er viktig, og OpenAI for bredden av tilleggstjenester.\n\nFor norske utviklere som skal velge, er anbefalingen å prøve begge. Opprett en konto på console.anthropic.com og platform.openai.com, test med din spesifikke brukscase, og sammenlign kvalitet og pris. Vercel AI SDK støtter begge leverandørene, så du kan bytte mellom dem med en enkelt linjeendring. Start med Sonnet 4.5 for de fleste prosjekter, og vurder Opus 4.6 hvis du trenger den aller beste kvaliteten.'
        }
    ]
};
