import type { Guide } from './types';

export const openaiApi: Guide = {
    slug: 'openai-api',
    tag: 'GUIDE \u00B7 OPENAI API',
    title: 'Kom i gang med OpenAI API',
    description: 'Lær hvordan du bruker OpenAI API til å bygge AI-drevne applikasjoner. Fra oppsett og autentisering til modellvalg, priser og avanserte funksjoner som function calling og structured outputs.',
    keywords: ['openai api', 'gpt api', 'openai api norsk', 'chatgpt api', 'openai api guide', 'ai api', 'gpt-5 api'],
    publishedDate: '2026-02-10',
    relatedSlugs: ['chatgpt', 'bygg-ai-chatbot', 'codex'],
    category: 'bygg-med-ai',
    sections: [
        {
            heading: 'Hva er OpenAI API?',
            content: 'ChatGPT er et ferdig produkt du bruker i nettleseren. OpenAI API er byggesteinene bak produktet, tilgjengelig som en programmerbar tjeneste. Med API-et kan du sende forespørsler direkte til OpenAIs språkmodeller fra din egen kode og bygge helt egne løsninger. Du bestemmer brukergrensesnittet, logikken og hvordan svarene brukes.\n\nDet betyr at du kan bygge alt fra kundeservice-chatboter og dokumentanalyseverktøy til AI-assistenter som er skreddersydd for en bestemt bransje. Du kan integrere AI i eksisterende applikasjoner, automatisere arbeidsflyter, eller lage helt nye produkter. Mange av tjenestene du bruker daglig, fra skriveassistenter til kodeverktøy, er bygget på OpenAI API under panseret.\n\nUtviklere velger API-et fordi det gir full kontroll. Du styrer hvilken modell som brukes, hvor kreative svarene skal være, hvor mye kontekst som sendes med, og hvordan resultatet presenteres. Du betaler kun for det du faktisk bruker, noe som gjør det fleksibelt for alt fra hobbyprojekter til produksjonstjenester med millioner av brukere.'
        },
        {
            heading: 'Oppsett og autentisering',
            content: 'For å komme i gang trenger du en konto på platform.openai.com. Det er OpenAIs utviklerportal, helt separat fra ChatGPT-abonnementet ditt. Etter registrering må du legge til en betalingsmetode under Billing-fanen. API-et har ingen fast månedsavgift. Du betaler per bruk basert på antall tokens du sender og mottar.\n\nNeste steg er å opprette en API-nøkkel. Gå til API Keys-seksjonen i dashbordet og klikk «Create new secret key». Nøkkelen vises bare en gang, så kopier den med en gang og lagre den trygt. Denne nøkkelen er passordet til API-kontoen din. Hvis noen får tak i den, kan de bruke API-et på din regning.\n\nBeste praksis er å lagre nøkkelen som en miljøvariabel. Opprett en .env-fil i prosjektet ditt med linjen OPENAI_API_KEY=din-nøkkel-her, og sørg for at .env er lagt til i .gitignore. Da unngår du å pushe nøkkelen til GitHub ved et uhell. I produksjon bruker du hemmelighetshåndtering i skyplattformen din, som Vercel Environment Variables eller AWS Secrets Manager.'
        },
        {
            heading: 'Ditt første API-kall',
            content: 'Det vanligste endepunktet er Chat Completions. Du sender en liste med meldinger og får et svar tilbake. Installer først OpenAI-biblioteket med «npm install openai». Deretter importerer du klienten, oppretter en instans med API-nøkkelen din, og kaller chat.completions.create med en modell og en meldingsarray. Meldingsarrayen inneholder objekter med en rolle (system, user eller assistant) og innhold. System-meldingen setter konteksten, mens user-meldingen er spørsmålet fra brukeren.\n\nSvaret kommer som et objekt der du finner den genererte teksten under choices[0].message.content. Du får også informasjon om hvor mange tokens forespørselen brukte, noe som er nyttig for å holde styr på kostnader. For lengre svar kan du bruke streaming ved å sette stream til true. Da får du svaret ord for ord i stedet for å vente på hele teksten, noe som gir en mye bedre brukeropplevelse i sanntid.\n\nEt viktig konsept er tokens. En token er omtrent tre til fire tegn på norsk. Både det du sender inn (input-tokens) og det modellen svarer med (output-tokens) telles. Du kan bruke OpenAIs tokenizer-verktøy for å estimere antall tokens i en tekst. Hold system-prompten kort og konsis, og begrens maks antall output-tokens med max_tokens-parameteren for å kontrollere kostnadene.'
        },
        {
            heading: 'Modeller og priser',
            content: 'OpenAI tilbyr flere modeller gjennom API-et, og valget avhenger av hva du bygger. GPT-5 er flaggskipmodellen med den beste kvaliteten på kompleks resonnering, koding og kreativ tekst. Den koster 1,25 dollar per million input-tokens og 10 dollar per million output-tokens. For de fleste produksjonsapplikasjoner er GPT-5 det naturlige valget når kvalitet er viktigst.\n\nFor resonnering finnes o3 og o4-mini. Disse modellene bruker ekstra tid på å tenke gjennom problemet og er spesielt sterke på matematikk, logikk og vitenskapelige oppgaver. o3 er den kraftigste, mens o4-mini gir mye av den samme resonneringskvaliteten til en lavere pris. Bruk resonneringsmodellene når oppgaven krever stegvis problemløsning eller nøyaktige beregninger.\n\nFor enklere oppgaver som klassifisering, uttrekk av data, eller raske svar der du trenger volum og lav kostnad, er GPT-4.1-mini og GPT-4.1-nano gode alternativer. De er vesentlig billigere og raskere, og for mange bruksområder er kvaliteten mer enn god nok. En smart strategi er å starte med en billigere modell og bare oppgradere for de oppgavene som faktisk trenger det. Du kan også sette bruksgrenser i dashbordet for å unngå overraskelser på fakturaen.'
        },
        {
            heading: 'Avanserte funksjoner',
            content: 'Function calling lar modellen be om å kalle funksjoner du har definert. Du beskriver funksjonene dine med navn, parametre og beskrivelser, og modellen bestemmer selv når det er relevant å bruke dem. For eksempel kan du definere en funksjon for å hente værdata, og når brukeren spør om været, returnerer modellen et strukturert kall til den funksjonen. Du kjører funksjonen, sender resultatet tilbake, og modellen formulerer svaret basert på de faktiske dataene. Dette gjør det mulig å bygge AI-assistenter som kan samhandle med databaser, API-er og eksterne systemer.\n\nStructured outputs lar deg tvinge modellen til å returnere JSON som følger et bestemt skjema. I stedet for å parse fritekst og håpe på riktig format, definerer du et JSON Schema og får garantert gyldig output. Dette er uvurderlig for produksjonsapplikasjoner der du trenger pålitelig datauttrekk, klassifisering, eller strukturert analyse.\n\nVision-funksjonaliteten lar deg sende bilder sammen med tekst. Du kan analysere skjermbilder, tolke diagrammer, lese tekst fra bilder, eller beskrive innhold. Embeddings-endepunktet konverterer tekst til tallvektorer som fanger betydningen av innholdet. Dette brukes til semantisk søk, anbefalingssystemer og RAG-løsninger der du henter relevant kontekst fra en kunnskapsbase. Kombinasjonen av disse funksjonene gjør OpenAI API til en allsidig plattform for å bygge avanserte AI-applikasjoner.'
        },
        {
            heading: 'Beste praksis og fallgruver',
            content: 'API-et har ratebegrensninger som styrer hvor mange forespørsler du kan sende per minutt og hvor mange tokens du kan bruke. Nye kontoer starter med lavere grenser som øker automatisk etter hvert som du bruker tjenesten. Bygg inn retry-logikk med eksponentiell backoff i koden din, slik at applikasjonen din håndterer midlertidige feil og 429-statuskoder uten å krasje.\n\nFeilhåndtering er avgjørende for en stabil applikasjon. Sjekk alltid for feil i API-svaret, håndter timeout-situasjoner, og ha en plan for når API-et er utilgjengelig. Logg forespørsler og svar slik at du kan feilsøke problemer. Sett fornuftige verdier for max_tokens og temperature, og valider input fra brukere før det sendes til modellen.\n\nDen største fallgruven for nybegynnere er å eksponere API-nøkkelen. Kall aldri OpenAI API direkte fra frontend-kode i nettleseren. Send alltid forespørslene gjennom din egen backend eller serverless-funksjon. Overvåk forbruket ditt i dashbordet på platform.openai.com, sett opp bruksgrenser og varsler, og roter API-nøklene med jevne mellomrom. Med disse grunnprinsippene på plass har du et solid fundament for å bygge pålitelige AI-applikasjoner.'
        }
    ]
};
