import type { Guide } from './types';

export const stripeAi: Guide = {
    slug: 'stripe-ai',
    tag: 'GUIDE \u00B7 STRIPE',
    title: 'Stripe for AI: Fakturering og monetisering',
    description: 'Lær hvordan du bruker Stripe til å fakturere og monetisere AI-produkter. Fra bruksbasert prising med Meters API og abonnementer til praktiske integrasjonstips for norske utviklere.',
    keywords: ['stripe ai', 'stripe billing', 'metered billing', 'bruksbasert prising', 'ai monetisering', 'stripe api', 'ai saas prising', 'stripe norsk'],
    publishedDate: '2026-02-10',
    relatedSlugs: ['openai-api', 'supabase-ai', 'bygg-ai-chatbot'],
    category: 'bygg-med-ai',
    sections: [
        {
            heading: 'Hvorfor Stripe for AI-produkter?',
            content: 'AI-produkter har unike faktureringsbehov som tradisjonelle betalingsløsninger ikke dekker godt. Når du bygger et produkt som bruker GPT-5 eller Claude, varierer kostnadene dine per bruker basert på hvor mye de faktisk bruker. En bruker som sender ti meldinger i måneden koster deg noen øre, mens en som sender tusen koster deg flere dollar. Du trenger et faktureringssystem som håndterer denne variasjonen.\n\nStripe er den mest utviklervennlige betalingsplattformen og har de siste årene bygget ut kraftige verktøy for nettopp bruksbasert fakturering. Dokumentasjonen finner du på docs.stripe.com, og administrasjonspanelet er på dashboard.stripe.com. Stripe støtter alt fra enkle engangsbetalinger til komplekse abonnementsmodeller med bruksbaserte komponenter.\n\nFor norske utviklere er Stripe et naturlig valg. Plattformen støtter norske kroner, norske bankkort, og har god dekning i hele Europa. Stripe håndterer PCI-compliance, sterk kundeautentisering (SCA) og lokal regulering automatisk, slik at du kan fokusere på produktet i stedet for betalingsinfrastruktur.'
        },
        {
            heading: 'Meters API: Betal per bruk',
            content: 'Stripe Meters API er bygget spesifikt for bruksbasert fakturering. En meter er en teller som sporer hvor mye en kunde bruker av tjenesten din. Du definerer en meter i Stripe, for eksempel «AI-tokens brukt» eller «API-kall», og rapporterer hendelser etter hvert som brukeren bruker tjenesten. Ved slutten av faktureringsperioden beregner Stripe automatisk hva kunden skylder basert på faktisk forbruk.\n\nArbeidsflyten er: du oppretter en meter i Stripe-dashbordet eller via API-et, knytter den til et prisingsoppsett på et abonnement, og sender meter events fra koden din når brukeren gjør noe fakturerbart. Stripe prosesserer hendelsene asynkront og aggregerer dem til fakturerbare beløp. Ved periodeslutt genereres fakturaen automatisk.\n\nDu rapporterer bruk via Stripe API-et med et enkelt kall som inkluderer kundens ID, meterens ID og antall enheter. For et AI-produkt kan det bety at du etter hvert API-kall rapporterer antall tokens som ble brukt. Stripe godtar også CSV-opplasting via dashbordet og bulkimport via Amazon S3 for store volum.\n\nMeters API erstatter den eldre Usage Records-tilnærmingen og gir bedre ytelse, fleksibilitet og nøyaktighet. Den støtter opptil tusenvis av hendelser per sekund per meter, som er mer enn nok for de aller fleste AI-produkter.'
        },
        {
            heading: 'Prisingsmodeller for AI',
            content: 'Det finnes flere måter å prise et AI-produkt på med Stripe, og den beste modellen avhenger av produktet ditt og målgruppen. Ren bruksbasert prising (betal-per-bruk) er den enkleste: kunden betaler kun for det de bruker, uten fast månedspris. Du setter en pris per enhet, for eksempel 0,01 krone per 1000 tokens, og Stripe beregner regningen. Dette fungerer godt for API-produkter der kundene er utviklere.\n\nHybrid-modellen er den mest vanlige for AI SaaS-produkter: en fast månedspris som inkluderer et visst forbruk, pluss en bruksbasert komponent for overskytende bruk. For eksempel kan Pro-planen til 199 kroner i måneden inkludere 100 000 tokens, og alt utover koster 0,01 krone per 1000 tokens. I Stripe setter du dette opp med en Subscription som har både en fast pris og en metered-komponent.\n\nKredittbaserte modeller er populære for forbruker-AI-produkter. Kunden kjøper en pakke med kreditter på forhånd, og disse brukes opp etter hvert. Du kan implementere dette med Stripe ved å selge kredittpakker som engangskjøp og spore forbruk i din egen database, eller ved å bruke prepaid credits via Stripe Billing.\n\nTrinnbasert prising (tiered pricing) lar deg sette forskjellige enhetspriser for forskjellige forbruksnivåer. De første 10 000 tokens kan koste 0,02 kroner per 1000, de neste 100 000 kan koste 0,01 kroner, og alt over det 0,005 kroner. Stripe støtter dette direkte via Graduated Pricing på prisingsoppsettet.'
        },
        {
            heading: 'Abonnementer med bruksgrenser',
            content: 'De fleste AI SaaS-produkter bruker abonnementsmodeller med forskjellige nivåer. Stripe Subscriptions håndterer dette med støtte for flere priser per abonnement, prøveperioder, oppgraderinger og nedgraderinger. Du definerer produkter og priser i Stripe-dashbordet, og bruker API-et til å opprette og administrere abonnementer.\n\nEn vanlig oppsett er tre nivåer: Gratis med begrenset bruk, Pro med høyere grenser, og Enterprise med ubegrenset eller tilpasset bruk. For hvert nivå oppretter du en Price i Stripe med den faste månedsprisen og eventuelt en metered-komponent. Stripe håndterer automatisk fakturering, betalingsinnkreving og mislykket betaling med smart retry-logikk.\n\nWebhooks er nøkkelen til å koble Stripe med applikasjonen din. Du lytter på hendelser som customer.subscription.created, invoice.paid og invoice.payment_failed for å oppdatere tilgangsnivåer, sende bekreftelser og håndtere betalingsproblemer. Stripe sender hendelser til en URL du konfigurerer, og du prosesserer dem i en API-rute i applikasjonen din.\n\nStripe Customer Portal lar kundene dine administrere abonnementet selv: oppgradere, nedgradere, oppdatere betalingsmetode og se faktureringshistorikk. Du konfigurerer portalen i Stripe-dashbordet og gir kundene en lenke til den fra applikasjonen din. Det sparer deg for å bygge all denne funksjonaliteten selv.'
        },
        {
            heading: 'Integrasjon i AI-appen din',
            content: 'For en typisk Next.js-app med AI-funksjonalitet ser integrasjonen slik ut: installer stripe-pakken med «npm install stripe», og opprett en Stripe-klient med API-nøkkelen din fra miljøvariablene. Du finner nøklene i Stripe-dashbordet under Developers.\n\nFor å spore tokenbruk legger du inn en rapporteringsfunksjon i AI-ruten din. Etter hvert API-kall til OpenAI eller Anthropic leser du token-forbruket fra svaret (det finnes i usage-feltet) og rapporterer det til Stripe via Meters API. Det er et enkelt POST-kall med kundens Stripe-ID og antall tokens. Gjør dette asynkront slik at det ikke bremser svartiden til brukeren.\n\nFor onboarding av nye betalende brukere er Stripe Checkout den raskeste veien. Du oppretter en Checkout Session med prisene dine, og Stripe håndterer hele betalingsflyten: kortinntasting, validering, SCA-autentisering og bekreftelse. Brukeren sendes tilbake til en suksess-URL i appen din, og du bruker webhooks for å aktivere tilgangen.\n\nEn viktig praksis er å sette forbruksgrenser i applikasjonen din. Selv om Stripe fakturerer basert på bruk, bør du sjekke brukerens forbruk mot planbegrensningene før du lar dem gjøre et nytt API-kall. Lagre gjeldende forbruk i databasen din og oppdater det etter hvert kall. Når grensen er nådd, vis en melding om å oppgradere.'
        },
        {
            heading: 'Priser, tips og fallgruver',
            content: 'Stripe tar 2,4 prosent pluss 2 kroner per vellykket korttransaksjon for norske kort. For internasjonale kort er det 2,9 prosent pluss 2 kroner. Det er ingen fast månedsavgift eller oppstartskostnad. Du betaler kun for vellykkede transaksjoner. For høyvolum-kunder finnes tilpassede priser.\n\nStripe Tax kan automatisk beregne og innkreve merverdiavgift i over 50 land og er tilgjengelig i Norge. For AI SaaS-produkter som selger til kunder i flere land er dette en enorm forenkling. Du aktiverer det i Stripe-dashbordet, og Stripe legger til riktig MVA basert på kundens lokasjon.\n\nDen vanligste fallgruven er å ikke sette forbruksgrenser. Uten grenser kan en enkelt bruker generere en enorm regning hos OpenAI eller Anthropic, og du fakturerer dem kanskje ikke til slutten av måneden. Implementer alltid sanntidssporing av forbruk og stopp tilgangen når grensen er nådd. En annen fallgruve er å ikke håndtere mislykkede betalinger. Stripe prøver automatisk på nytt, men du bør pause tjenesten for kunder med utestående betalinger.\n\nEt godt tips er å alltid ha et gratisnivå. Det senker terskelen for nye brukere og lar dem teste produktet ditt før de betaler. Sett en lav grense, for eksempel 10 000 tokens per måned, som er nok til å oppleve verdien men ikke nok til seriøs bruk. Stripe gjør det enkelt å håndtere gratis-til-betalt-overgangen med Checkout og Customer Portal.'
        }
    ]
};
