import type { Guide } from './types';

export const windsurf: Guide = {
    slug: 'windsurf',
    tag: 'GUIDE \u00B7 WINDSURF',
    title: 'Windsurf: AI-editoren fra Codeium',
    description: 'En komplett guide til Windsurf, AI-editoren som het Codeium. Lær om Cascade, priser, agentisk koding og hvordan Windsurf sammenligner med Cursor og Copilot.',
    keywords: ['windsurf', 'windsurf ai', 'codeium', 'windsurf vs cursor', 'ai kodeeditor', 'cascade ai'],
    publishedDate: '2026-02-10',
    relatedSlugs: ['cursor', 'github-copilot', 'claude-code'],
    category: 'koding',
    sections: [
        {
            heading: 'Hva er Windsurf?',
            content: 'Windsurf er en AI-drevet kodeeditor tilgjengelig på windsurf.com. Den het opprinnelig Codeium og ble startet i 2022 av Varun Mohan og Douglas Chen. Codeium begynte som en gratis AI-kompletteringsutvidelse for flere editorer, men i november 2024 lanserte selskapet sin egen editor under navnet Windsurf. Editoren er bygget på VS Code, så den føles kjent for de fleste utviklere.\n\nI desember 2025 ble det kjent at OpenAI kjøpte Windsurf for rundt 3 milliarder dollar, en av de største oppkjøpene i AI-verktøymarkedet noensinne. Oppkjøpet betyr at Windsurf nå er en del av OpenAI-familien, men editoren lever videre som et eget produkt. OpenAI har signalisert at de vil bruke Windsurf-teknologien til å styrke sine egne kodingsverktøy, samtidig som Windsurf fortsetter å operere selvstendig.\n\nDet som gjorde Codeium populært var at de tilbød en sjenerøs gratisversjon da de fleste konkurrentene kostet penger. Med Windsurf tok de steget videre og bygget en hel editor rundt AI, med Cascade som flaggskipfunksjon for agentisk koding.'
        },
        {
            heading: 'Priser og planer',
            content: 'Windsurf har en gratisplan som gir deg tilgang til grunnleggende AI-funksjoner uten å betale noe. Du får autokomplettering og et begrenset antall forespørsler til Cascade og chat per måned. For hobbyprosjekter og studenter er dette et godt utgangspunkt.\n\nPro-planen koster 15 dollar i måneden og er det de fleste seriøse utviklere velger. Du får ubegrenset autokomplettering, betydelig flere Cascade-forespørsler, tilgang til de beste AI-modellene, og prioritert hastighet. Det er her Windsurf virkelig begynner å skinne.\n\nTeams-planen er rettet mot bedrifter og koster 30 dollar per bruker per måned. Den inkluderer alt i Pro pluss teamadministrasjon, sentralisert fakturering, og muligheten til å styre tilgang og policyer for hele organisasjonen.\n\nFor store virksomheter finnes det en Enterprise-plan med tilpasset prising som legger til ting som egne modeller, SSO-integrasjon, og dedikert support. Prisene kan ha blitt justert etter OpenAI-oppkjøpet, så sjekk windsurf.com for oppdatert informasjon.'
        },
        {
            heading: 'Cascade: Agentisk koding',
            content: 'Cascade er Windsurfs viktigste funksjon og det som skiller den fra vanlige AI-kompletteringsverktøy. Det er en agentisk kodemodus der du beskriver hva du vil oppnå, og Windsurf håndterer resten. Cascade leser relevante filer i prosjektet ditt, planlegger endringene som trengs, og implementerer dem på tvers av flere filer samtidig.\n\nDet som gjør Cascade spesielt er at den opprettholder kontekst gjennom hele arbeidsflyten. Den husker hva du har gjort tidligere i samtalen og forstår sammenhenger på tvers av kodebasen. Du kan be den lage en ny funksjon, og den vet hvilke eksisterende filer som må oppdateres, hvilke importer som trengs, og hvordan den nye koden passer inn i arkitekturen.\n\nCascade kan også kjøre terminalkommandoer, installere avhengigheter, og kjøre tester som en del av arbeidsflyten. Du ser alt den gjør i sanntid og kan godkjenne eller avvise hvert steg. Det gir deg kontrollen tilbake uten at du må gjøre alt manuelt.\n\nFor mange utviklere er Cascade grunnen til at de velger Windsurf fremfor alternativer. Det er en av de tidligste og mest modne implementasjonene av agentisk koding i en editor, og den har blitt betydelig forbedret gjennom 2025 og inn i 2026.'
        },
        {
            heading: 'Tab-komplettering og kodekontekst',
            content: 'Ved siden av Cascade har Windsurf en kraftig tab-komplettering som kalles Supercomplete. Den fungerer som du forventer: du skriver kode, og Windsurf foreslår resten. Men den er smartere enn vanlig autokomplettering fordi den tar hensyn til hele prosjektet ditt, ikke bare filen du jobber i.\n\nSupercomplete bruker kodebaseindeksering for å forstå strukturen i prosjektet. Den vet hvilke funksjoner som finnes, hvilke typer som er definert, og hvordan ulike deler av koden henger sammen. Resultatene er forslag som faktisk passer inn i konteksten din, ikke bare generisk kode.\n\nWindsurf har også en innebygd chat der du kan stille spørsmål om koden din. Du kan markere en kodeblokk og be om en forklaring, eller spørre om hvordan du bør implementere noe. Chatten deler kontekst med resten av editoren, så den forstår hva du jobber med.\n\nEn funksjon mange setter pris på er at Windsurf automatisk oppdager og indekserer hele kodebasen din når du åpner et prosjekt. Du trenger ikke konfigurere noe. Den bygger en forståelse av prosjektet i bakgrunnen og bruker dette til å forbedre alle AI-forslag.'
        },
        {
            heading: 'Windsurf vs. Cursor vs. VS Code + Copilot',
            content: 'Windsurf, Cursor og VS Code med Copilot er de tre store alternativene for AI-assistert koding i dag. Alle tre har sine styrker, og valget avhenger av hva du prioriterer.\n\nWindsurf er det rimeligste alternativet med en sjenerøs gratisplan og Pro til 15 dollar mot Cursors 20 dollar. Cascade var en av de første agentiske kodemodusene på markedet, og den er fortsatt blant de beste. Windsurf har også fordelen av at den har vært gratis lenger enn konkurrentene, noe som har gitt den en stor brukerbase. Med OpenAI i ryggen kan man forvente kraftige modeller fremover.\n\nCursor har et mer modent agentsystem med funksjoner som Composer og Subagents. Den støtter flere AI-modeller samtidig og lar deg kjede dem sammen. For erfarne utviklere som vil ha maksimal fleksibilitet er Cursor ofte førstevalget. Cursor koster 20 dollar per måned for Pro.\n\nVS Code med GitHub Copilot er det minst forstyrrende alternativet. Du beholder editoren du kjenner og legger til AI som en utvidelse. Copilot er best for de som vil ha diskret hjelp uten å bytte editor. Med gratisplanen som gir 2000 kompletteringer i måneden er terskelen lav.\n\nFlere utviklere bruker mer enn ett verktøy. En vanlig kombinasjon er Copilot for hverdagskoding og Windsurf eller Cursor når du trenger agentisk hjelp med større oppgaver.'
        },
        {
            heading: 'Kom i gang med Windsurf',
            content: 'For å komme i gang laster du ned Windsurf fra windsurf.com. Editoren er tilgjengelig for macOS, Windows og Linux. Installasjonen tar bare noen minutter, og siden den er basert på VS Code kan du importere innstillinger, utvidelser og temaer fra VS Code med et par klikk.\n\nNår du åpner Windsurf for første gang, oppretter du en konto eller logger inn med GitHub. Åpne et prosjekt, og Windsurf begynner automatisk å indeksere kodebasen din i bakgrunnen. Etter noen sekunder til minutter, avhengig av prosjektets størrelse, er AI-en klar til å hjelpe deg.\n\nFor å prøve Cascade, trykk Cmd+I på Mac eller Ctrl+I på Windows og Linux. Skriv hva du vil oppnå, for eksempel lag en ny API-rute for brukerregistrering med validering. Cascade analyserer prosjektet ditt, foreslår endringer i relevante filer, og du kan godkjenne dem steg for steg.\n\nTab-komplettering fungerer med en gang. Bare begynn å skrive kode, og Windsurf foreslår resten. Trykk Tab for å godta, eller fortsett å skrive for å ignorere forslaget. Etter noen timers bruk vil du merke at forslagene blir stadig mer relevante etter hvert som Windsurf lærer prosjektet ditt å kjenne.'
        }
    ]
};
